export const participants = [
  "prahenstark",
  "Abhijeet-Anand-01",
  "Jyo561",
  "arpanaditya",
  "Sanjana-027",
  "ShivamChoudhary17",
  "amitosh2578",
  "ankitrajbiswal",
  "somyachoudhury",
  "SidharthSarangi",
  "soumyarath3277",
  "adarshzpatel",
  "MannyP31",
];
